const prisma = require("../../config/db");
const range = (query) => ({ ...(query.from ? { gte: new Date(query.from) } : {}), ...(query.to ? { lte: new Date(query.to) } : {}) });
const amount = (value) => Number(value || 0).toFixed(2);
const getDashboard = async (tenantId) => {
  const tenant = BigInt(tenantId);
  const [beds, occupiedBeds, bookings, payments, guests, openComplaints, inventory] = await Promise.all([
    prisma.beds.count({ where: { tenant_id: tenant } }), prisma.beds.count({ where: { tenant_id: tenant, status: "OCCUPIED" } }),
    prisma.bookings.count({ where: { tenant_id: tenant } }), prisma.payments.aggregate({ where: { tenant_id: tenant, status: "COMPLETED" }, _sum: { amount: true } }),
    prisma.users.count({ where: { tenant_id: tenant, role: "GUEST" } }), prisma.complaints.count({ where: { tenant_id: tenant, status: { in: ["OPEN", "IN_PROGRESS"] } } }),
    prisma.inventory_items.count({ where: { tenant_id: tenant, current_stock: { lte: prisma.inventory_items.fields.min_stock_level } } }).catch(() => 0),
  ]);
  return { beds: { total: beds, occupied: occupiedBeds, available: beds - occupiedBeds, occupancyPercent: beds ? Number(((occupiedBeds / beds) * 100).toFixed(2)) : 0 }, bookings, revenue: amount(payments._sum.amount), guests, openComplaints, lowStockItems: inventory };
};
const occupancyReport = async (tenantId) => { const beds = await prisma.beds.groupBy({ by: ["status"], where: { tenant_id: BigInt(tenantId) }, _count: { id: true } }); return beds.map((row) => ({ status: row.status, count: row._count.id })); };
const revenueReport = async (tenantId, query) => { const rows = await prisma.payments.groupBy({ by: ["method"], where: { tenant_id: BigInt(tenantId), status: "COMPLETED", ...(query.from || query.to ? { paid_at: range(query) } : {}) }, _sum: { amount: true }, _count: { id: true } }); return rows.map((row) => ({ method: row.method, payments: row._count.id, amount: amount(row._sum.amount) })); };
const guestReport = async (tenantId) => { const rows = await prisma.users.findMany({ where: { tenant_id: BigInt(tenantId), role: "GUEST" }, include: { bookings_as_guest: { select: { id: true, status: true } } }, orderBy: { created_at: "desc" } }); return rows.map((guest) => ({ id: guest.id.toString(), name: guest.name, phone: guest.phone, bookings: guest.bookings_as_guest.length, activeBookings: guest.bookings_as_guest.filter((booking) => booking.status === "CHECKED_IN").length })); };
const bookingReport = async (tenantId) => { const rows = await prisma.bookings.groupBy({ by: ["status"], where: { tenant_id: BigInt(tenantId) }, _count: { id: true }, _sum: { total_amount: true } }); return rows.map((row) => ({ status: row.status, count: row._count.id, value: amount(row._sum.total_amount) })); };
const paymentReport = async (tenantId) => { const rows = await prisma.payments.groupBy({ by: ["status"], where: { tenant_id: BigInt(tenantId) }, _count: { id: true }, _sum: { amount: true } }); return rows.map((row) => ({ status: row.status, count: row._count.id, amount: amount(row._sum.amount) })); };
const inventoryReport = async (tenantId) => { const rows = await prisma.inventory_items.findMany({ where: { tenant_id: BigInt(tenantId) }, orderBy: { name: "asc" } }); return rows.map((item) => ({ id: item.id.toString(), name: item.name, category: item.category, stock: item.current_stock.toString(), minStock: item.min_stock_level.toString(), lowStock: Number(item.current_stock) <= Number(item.min_stock_level) })); };
const staffPerformance = async (tenantId) => { const rows = await prisma.audit_logs.groupBy({ by: ["user_id", "action"], where: { tenant_id: BigInt(tenantId), user_id: { not: null } }, _count: { id: true } }); return rows.map((row) => ({ userId: row.user_id.toString(), action: row.action, count: row._count.id })); };
const complaintReport = async (tenantId) => { const rows = await prisma.complaints.groupBy({ by: ["status", "priority"], where: { tenant_id: BigInt(tenantId) }, _count: { id: true } }); return rows.map((row) => ({ status: row.status, priority: row.priority, count: row._count.id })); };
const feedbackReport = async (tenantId) => { const data = await prisma.feedback.aggregate({ where: { tenant_id: BigInt(tenantId) }, _count: { id: true }, _avg: { overall_rating: true, service_rating: true, cleanliness_rating: true, value_rating: true } }); return { total: data._count.id, averageOverall: data._avg.overall_rating || 0, averageService: data._avg.service_rating || 0, averageCleanliness: data._avg.cleanliness_rating || 0, averageValue: data._avg.value_rating || 0 }; };
const bi = async (tenantId, days) => { const from = new Date(); from.setDate(from.getDate() - days); const [bookings, payments, feedback] = await Promise.all([prisma.bookings.count({ where: { tenant_id: BigInt(tenantId), created_at: { gte: from } } }), prisma.payments.aggregate({ where: { tenant_id: BigInt(tenantId), status: "COMPLETED", paid_at: { gte: from } }, _sum: { amount: true } }), prisma.feedback.aggregate({ where: { tenant_id: BigInt(tenantId), created_at: { gte: from } }, _avg: { overall_rating: true } })]); return { periodDays: days, bookings, revenue: amount(payments._sum.amount), averageFeedback: feedback._avg.overall_rating || 0 }; };
module.exports = { getDashboard, occupancyReport, revenueReport, guestReport, bookingReport, paymentReport, inventoryReport, staffPerformance, complaintReport, feedbackReport, bi };
