const crypto = require("crypto"); const prisma = require("../../config/db"); const { recordAudit } = require("../../common/audit.service");
const fail = (message, status, code) => { const error = new Error(message); error.status = status; error.code = code; throw error; };
const formatFeedback = (item) => ({ id: item.id.toString(), bookingId: item.booking_id?.toString() || null, guestId: item.guest_id.toString(), overallRating: item.overall_rating, cleanlinessRating: item.cleanliness_rating, serviceRating: item.service_rating, valueRating: item.value_rating, comment: item.comment, status: item.status, createdAt: item.created_at });
const formatComplaint = (item) => ({ id: item.id.toString(), complaintCode: item.complaint_code, bookingId: item.booking_id?.toString() || null, guestId: item.guest_id.toString(), category: item.category, subject: item.subject, description: item.description, priority: item.priority, status: item.status, assignedTo: item.assigned_to?.toString() || null, resolution: item.resolution, resolvedAt: item.resolved_at, createdAt: item.created_at });
const resolveGuest = (tenantId, requestedGuestId, actor) => { const guestId = actor.role === "GUEST" ? actor.userId : requestedGuestId; if (!guestId) fail("guestId is required", 400, "VALIDATION_ERROR"); return BigInt(guestId); };
const ensureBooking = async (tx, tenantId, bookingId, guestId) => { if (!bookingId) return null; const booking = await tx.bookings.findFirst({ where: { id: BigInt(bookingId), tenant_id: BigInt(tenantId), guest_id: guestId } }); if (!booking) fail("Booking not found for guest", 404, "BOOKING_NOT_FOUND"); return booking.id; };
const createFeedback = async (tenantId, data, actor, req) => {
  const guestId = resolveGuest(tenantId, data.guestId, actor);
  const feedback = await prisma.$transaction(async (tx) => { await ensureBooking(tx, tenantId, data.bookingId, guestId); const created = await tx.feedback.create({ data: { tenant_id: BigInt(tenantId), booking_id: data.bookingId ? BigInt(data.bookingId) : null, guest_id: guestId, overall_rating: data.overallRating, cleanliness_rating: data.cleanlinessRating || null, service_rating: data.serviceRating || null, value_rating: data.valueRating || null, comment: data.comment || null } }); await recordAudit({ tenantId, userId: actor.userId, action: "FEEDBACK_CREATED", entityType: "FEEDBACK", entityId: created.id, req, client: tx }); return created; });
  return formatFeedback(feedback);
};
const feedbackAnalysis = async (tenantId) => { const [summary, rows] = await Promise.all([prisma.feedback.aggregate({ where: { tenant_id: BigInt(tenantId) }, _avg: { overall_rating: true, cleanliness_rating: true, service_rating: true, value_rating: true }, _count: { id: true } }), prisma.feedback.groupBy({ by: ["overall_rating"], where: { tenant_id: BigInt(tenantId) }, _count: { id: true }, orderBy: { overall_rating: "asc" } })]); return { total: summary._count.id, averages: { overall: summary._avg.overall_rating || 0, cleanliness: summary._avg.cleanliness_rating || 0, service: summary._avg.service_rating || 0, value: summary._avg.value_rating || 0 }, distribution: rows.map((row) => ({ rating: row.overall_rating, count: row._count.id })) }; };
const createComplaint = async (tenantId, data, actor, req) => { const guestId = resolveGuest(tenantId, data.guestId, actor); const complaint = await prisma.$transaction(async (tx) => { await ensureBooking(tx, tenantId, data.bookingId, guestId); const created = await tx.complaints.create({ data: { tenant_id: BigInt(tenantId), booking_id: data.bookingId ? BigInt(data.bookingId) : null, guest_id: guestId, complaint_code: `CMP-${crypto.randomBytes(5).toString("hex").toUpperCase()}`, category: data.category, subject: data.subject, description: data.description, priority: data.priority } }); await recordAudit({ tenantId, userId: actor.userId, action: "COMPLAINT_CREATED", entityType: "COMPLAINT", entityId: created.id, req, client: tx }); return created; }); return formatComplaint(complaint); };
const listComplaints = async (tenantId, status) => (await prisma.complaints.findMany({ where: { tenant_id: BigInt(tenantId), ...(status ? { status } : {}) }, orderBy: [{ priority: "desc" }, { created_at: "desc" }] })).map(formatComplaint);
const updateComplaint = async (tenantId, complaintId, data, actor, req) => { const complaint = await prisma.$transaction(async (tx) => { const current = await tx.complaints.findFirst({ where: { id: BigInt(complaintId), tenant_id: BigInt(tenantId) } }); if (!current) fail("Complaint not found", 404, "NOT_FOUND"); if (data.assignedTo) { const assignee = await tx.users.findFirst({ where: { id: BigInt(data.assignedTo), tenant_id: BigInt(tenantId), status: "ACTIVE" } }); if (!assignee) fail("Assignee not found", 404, "ASSIGNEE_NOT_FOUND"); } const updated = await tx.complaints.update({ where: { id: current.id }, data: { status: data.status, assigned_to: data.assignedTo ? BigInt(data.assignedTo) : current.assigned_to, resolution: data.resolution ?? current.resolution, resolved_at: ["RESOLVED", "CLOSED"].includes(data.status) ? new Date() : null, updated_at: new Date() } }); await recordAudit({ tenantId, userId: actor.userId, action: "COMPLAINT_UPDATED", entityType: "COMPLAINT", entityId: updated.id, oldValues: { status: current.status }, newValues: { status: updated.status }, req, client: tx }); return updated; }); return formatComplaint(complaint); };
module.exports = { createFeedback, feedbackAnalysis, createComplaint, listComplaints, updateComplaint };
